apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ee8r8vbko-python
  janus-idp.io/tekton: ee8r8vbko-python
  backstage.io/kubernetes-id: ee8r8vbko-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ee8r8vbko-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
