apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ee8r8vbko-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ee8r8vbko-python 
  name: ee8r8vbko-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ee8r8vbko-python 
